import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import style from "styled-jsx/style";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  
}>) {
  return (
    <html lang="en" className="light" >
      <body 
        className={`${geistSans.variable} {{color-scheme:"light"}} ${geistMono.variable} antialiased`}
      >
<ThemeProvider
  
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
         
          >
            <Navbar />
            <main className="max-w-2xl mx-auto px-4">
               {children}</main>
       
        </ThemeProvider >
        <Footer />
  
      </body> 
      
    </html>

  );
}
